apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: vsposato/bugtrackerjhipster
      context: ../BugTrackerJHipster
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
